name: Dealls Assessment Test June 2025

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
        skip_report:
            description: 'Skip Cypress report step'
            required: false
            default: 'false'

jobs:
  dealls-assessment-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Clean and install dependencies
        run: rm -rf node_modules package-lock.json && npm install

      - name: Fix Cypress permissions
        run: chmod +x node_modules/.bin/cypress

      - name: Debug CI
        run: ls -lah node_modules/.bin/

      - name: Run Cypress tests
        if: ${{ github.event.inputs.skip_report != 'true' }}
        run: npm run test:only

      - name: Debug Report Folder
        if: ${{ github.event.inputs.skip_report != 'true' }}
        run: ls -lah cypress/reports/mochawesome-report

      - name: Run Report
        if: ${{ github.event.inputs.skip_report != 'true' }}
        run: npm run report

      - name: Upload Cypress Reports
        if: ${{ github.event.inputs.skip_report != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome-report